apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-db
  labels:
    app: teastore
    run: teastore-db
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-db
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-db
    spec:
      containers:
      - name: teastore-db
        image: descartesresearch/teastore-db
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-db
  labels:
    app: teastore
    run: teastore-db
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    run: teastore-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-all
  labels:
    app: teastore
    run: teastore-all
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-all
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-all
    spec:
      containers:
      - name: teastore-all
        image: descartesresearch/teastore-all
        ports:
        - containerPort: 8080
        env:
          - name: USE_POD_IP
            value: "true"
          - name: DB_HOST
            value: "teastore-db"
          - name: DB_PORT
            value: "3306"
          - name: RABBITMQ_HOST
            value: "teastore-kieker-rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-all
  labels:
    app: teastore
    run: teastore-all
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30080
    protocol: TCP
  selector:
    run: teastore-all